name: Run dev tests

on:
  workflow_dispatch:

permissions:
  contents: read

# if a new request comes through, cancel previous workflow and start again
concurrency:
  group: '${{ github.workflow }} @ ${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:

  run-tests:

    strategy:
        matrix:
          os: [ "windows-latest", "macos-latest" ]

    name: Run dev tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 8

    defaults:
      run:
        shell: bash

  # Build the test suite
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: main
      - run: git pull origin main

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Install wheel package
        run: pip install wheel

      - name: Install pyuiauto wheel
        run: pip install dist/*.whl
      
      - name: Install pytest
        run: |
          pip install pytest
          pytest --version

  # Run dev tests
      - name: Run OS compatibility tests
        run: echo "Running OS compatibility tests"
      - run: |
          pytest tests/test_os.py -vvv -s --noconftest --log-cli-level=DEBUG -p no:faulthandler

      - name: Run general package tests
        run: echo "Running general package tests"
      - run: |
          pytest tests/test_pyuiauto.py -vvv -s --log-cli-level=DEBUG -p no:faulthandler
